"""
SQLAlchemy ORM Model: Recommendation
Stores generated recommendations with scores and explanations for audit/analytics.
"""
import uuid
from datetime import datetime
from sqlalchemy import Column, String, Float, Boolean, Integer, DateTime, JSON, ForeignKey
from sqlalchemy.orm import relationship

from app.db.session import Base


class Recommendation(Base):
    """A recommendation generated by the AI engine for a candidate."""

    __tablename__ = "recommendations"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))

    candidate_id = Column(
        String(36),
        ForeignKey("candidates.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    internship_id = Column(
        String(36),
        ForeignKey("internships.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Scores from each engine component
    content_score = Column(Float, nullable=False, default=0.0)
    collaborative_score = Column(Float, nullable=False, default=0.0)
    affirmative_score = Column(Float, nullable=False, default=0.0)
    final_score = Column(Float, nullable=False, default=0.0)

    # Explanation (JSON blob with reasons, skill alignment, etc.)
    explanation = Column(JSON, nullable=True)

    # Tracking: did the user engage with this recommendation?
    was_clicked = Column(Boolean, default=False)
    was_applied = Column(Boolean, default=False)

    # Position shown to user
    display_rank = Column(Integer, nullable=True)

    generated_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    candidate = relationship("Candidate", back_populates="recommendations")
    internship = relationship("Internship", back_populates="recommendations")

    @property
    def match_percentage(self) -> int:
        """Convert final_score (0-1) to display percentage (0-100)."""
        return min(99, max(1, int(self.final_score * 100)))

    def __repr__(self):
        return f"<Recommendation(candidate={self.candidate_id}, score={self.final_score:.2f})>"
